linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - gofmt
    - goimports
    - misspell
    - unconvert
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true